---

# Main tasks file for enpass role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::enpass'
    - 'role::enpass::init'
